# action.yml
name: 'Push kaggle dataset'
description: 'Upload dataset from github repository to kaggle'
inputs:

  id:
    description: "Dataset identifier in format {username}/{dataset})."
    required: false
    default: "{KAGGLE_USERNAME}/{GITHUB_REPO_NAME}"

  files:
    description: "Files to upload."
    required: true
    default: "*.csv"

  title:
    description: "Title of the dataset, only if it has to be created."
    required: false
    default: "dataset id"

  subtitle:
    description: "Subtitle of the dataset. Must be between 20 and 80 characters"
    required: false
    default: ""

  description:
    description: "Description of the dataset, only if it has to be created."
    required: false
    default: ""

  is_public:
    description: "Create publicly (default is private)."
    required: false
    default: false

  version_notes:
    description: 'Message describing the new version'
    required: false
    default: commit message

outputs:
  url: # id of output
    description: 'URL of the dataset'

runs:
  using: 'docker'
  image: 'jaimevalero78/push-kaggle-dataset'
